# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from ._enums import *

__all__ = [
    'Child',
]

@pulumi.output_type
class Child(dict):
    def __init__(__self__, *,
                 age: Optional[int] = None,
                 name: Optional[str] = None):
        Child.__configure__(
            age=age,
            name=name,
            __setter=lambda key, value: pulumi.set(__self__, key, value),
        )
    @staticmethod
    def __configure__(*,
             age: Optional[int] = None,
             name: Optional[str] = None,
             __setter=lambda key, value: ...):
        if age is not None:
            __setter("age", age)
        if name is not None:
            __setter("name", name)

    @property
    @pulumi.getter
    def age(self) -> Optional[int]:
        return pulumi.get(self, "age")

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        return pulumi.get(self, "name")


