# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'BastionShareableLink',
]

@pulumi.input_type
class BastionShareableLink:
    def __init__(__self__, *,
                 vm: str):
        """
        Bastion Shareable Link.
        :param str vm: Reference of the virtual machine resource.
        """
        BastionShareableLink.__configure__(
            vm=vm,
            __setter=lambda key, value: pulumi.set(__self__, key, value),
        )
    @staticmethod
    def __configure__(*,
             vm: str,
             __setter=lambda key, value: ...):
        __setter("vm", vm)

    @property
    @pulumi.getter
    def vm(self) -> str:
        """
        Reference of the virtual machine resource.
        """
        return pulumi.get(self, "vm")

    @vm.setter
    def vm(self, value: str):
        pulumi.set(self, "vm", value)


