// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	pux "github.com/pulumi/pulumi/sdk/v3/go/pulumix"
	"simple-resource-schema/example/internal"
)

type FooResource struct {
	pulumi.ResourceState

	Foo pux.GPtrOutput[Resource, ResourceOutput] `pulumi:"foo"`
}

// NewFooResource registers a new resource with the given unique name, arguments, and options.
func NewFooResource(ctx *pulumi.Context,
	name string, args *FooResourceArgs, opts ...pulumi.ResourceOption) (*FooResource, error) {
	if args == nil {
		args = &FooResourceArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FooResource
	err := ctx.RegisterRemoteComponentResource("foo::FooResource", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type fooResourceArgs struct {
	Foo pulumi.Input[Resource] `pulumi:"foo"`
}

// The set of arguments for constructing a FooResource resource.
type FooResourceArgs struct {
	Foo pulumi.Input[*Resource]
}

func (FooResourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*fooResourceArgs)(nil)).Elem()
}

type FooResourceOutput struct{ *pulumi.OutputState }

func (FooResourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FooResource)(nil)).Elem()
}

func (o FooResourceOutput) ToFooResourceOutput() FooResourceOutput {
	return o
}

func (o FooResourceOutput) ToFooResourceOutputWithContext(ctx context.Context) FooResourceOutput {
	return o
}

func (o FooResourceOutput) ToOutput(ctx context.Context) pulumix.Output[*FooResource] {
	return pulumix.Output[*FooResource]{
		OutputState: o.OutputState,
	}
}

func (o FooResourceOutput) Foo() pux.GPtrOutput[Resource, ResourceOutput] {
	return pux.Apply(o, func(v *FooResource) pux.GPtrOutput[Resource, ResourceOutput] { return v.Foo })
}

func init() {
	pulumi.RegisterOutputType(FooResourceOutput{})
}
