# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'PetArgs',
]

@pulumi.input_type
class PetArgs:
    def __init__(__self__, *,
                 name: Optional[pulumi.Input[str]] = None):
        PetArgs.__configure__(
            name=name,
            __setter=lambda key, value: pulumi.set(__self__, key, value),
        )
    @staticmethod
    def __configure__(*,
             name: Optional[pulumi.Input[str]] = None,
             __setter=lambda key, value: ...):
        if name is not None:
            __setter("name", name)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)


