# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'Pet',
]

@pulumi.output_type
class Pet(dict):
    def __init__(__self__, *,
                 name: Optional[str] = None):
        Pet.__configure__(
            name=name,
            __setter=lambda key, value: pulumi.set(__self__, key, value),
        )
    @staticmethod
    def __configure__(*,
             name: Optional[str] = None,
             __setter=lambda key, value: ...):
        if name is not None:
            __setter("name", name)

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        return pulumi.get(self, "name")


