# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'TopLevel',
]

@pulumi.output_type
class TopLevel(dict):
    def __init__(__self__, *,
                 buzz: Optional[str] = None):
        TopLevel.__configure__(
            buzz=buzz,
            __setter=lambda key, value: pulumi.set(__self__, key, value),
        )
    @staticmethod
    def __configure__(*,
             buzz: Optional[str] = None,
             __setter=lambda key, value: ...):
        if buzz is not None:
            __setter("buzz", buzz)

    @property
    @pulumi.getter
    def buzz(self) -> Optional[str]:
        return pulumi.get(self, "buzz")


