# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'Sandwich',
]

@pulumi.output_type
class Sandwich(dict):
    def __init__(__self__, *,
                 bread: Optional[str] = None,
                 veggies: Optional[Sequence[str]] = None):
        Sandwich.__configure__(
            bread=bread,
            veggies=veggies,
            __setter=lambda key, value: pulumi.set(__self__, key, value),
        )
    @staticmethod
    def __configure__(*,
             bread: Optional[str] = None,
             veggies: Optional[Sequence[str]] = None,
             __setter=lambda key, value: ...):
        if bread is not None:
            __setter("bread", bread)
        if veggies is not None:
            __setter("veggies", veggies)

    @property
    @pulumi.getter
    def bread(self) -> Optional[str]:
        return pulumi.get(self, "bread")

    @property
    @pulumi.getter
    def veggies(self) -> Optional[Sequence[str]]:
        return pulumi.get(self, "veggies")


